# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- powershell: |
    write-host "Agent.BuildDirectory:" $(Agent.BuildDirectory)
    write-host "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"
    write-host "My Variable:" $(myOutputVar)
  name: ShowSomeVariables

- powershell: |
   # Write your powershell commands here.
   Write-Host "Listing PS1 files on C:\"
   gci -Path C:\ *.ps1 -Recurse
  displayName: "PS Script to list PS1 files #01"
  errorActionPreference: continue
  workingDirectory: '.'

- powershell: |
   Write-Host "Listing ps1 files:" $(Build.Repository.LocalPath)
   gci -Path $(Build.Repository.LocalPath).ps1 -Recurse
   
  errorActionPreference: continue
  workingDirectory: '.'
  displayName: 'PS Script to list PS1 files #02'
