# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"
  name: setvarStep

- powershell: write-host "myOutputVar:" $(setvarStep.myOutputVar)
  name: echovar

- powershell: write-host "Agent.BuildDirectory:" $(Agent.BuildDirectory)
  name: AgentBuildDir

- powershell: [task.setvariable variable=BuildFormat]$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
  name SetBuildFormat

- powershell: Write-host "build format:" $(SetBuildFormat.BuildFormat)
  name: EchoBuildFormat
